// <auto-generated />
namespace Online_Story_Maker_Sridhar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class LastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201504220022117_LastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
